<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/06/19 12:53:57
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
