#ルーティングを追加していく。
question:
  url:   /question/show/:stripped_title
  param: { module: question, action: show }

#ページの移動
popular_questions:
  url:   /index/list
  param: { module: question, action: list }

#ページの移動
recent_questions:
  url:   /question/recent/:page
  param: { module: question, action: recent,page: 1 }

login:
  url:   /login
  param: { module: user, action: login }

recent_answers:
  url:   /answer/recent/:page
  param: { module: answer, action: recent,page: 1 }

user_profile:
  url:   /user/:nickname
  param: { module: user, action: show}

add_question:
  url:   /question/add
  param: { module: question, action: add}

add_answer:
  url:   /add_anwser
  param: { module: answer, action: add}


#フィード
feed_popular_questions:
  url:   /feed/popular
  param: { module: feed, action: popular }


user_require_password:
  url:   /password_request
  param: { module: user, action: passwordRequest }

#tagに関してのルーティング
tag:
  url:   /tag/:tag/:page
  param: { module: tag, action: show, page: 1 }


#ここふがデフォルト設定
# default rules。
homepage:
  url:   /
  param: { module: question, action: list }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*







