#ルーティングを変更した
question:
  url:   /question/:stripped_title
  param: { module: question, action: show }

#ページの移動
popular_questions:
  url:   /index/:page
  param: { module: question, action: list }

# default rules
homepage:
  url:   /
  param: { module: question, action: list }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*

