default:
  http_metas:
    content-type: text/html
  components:
    sidebar:      [sidebar, default]

  metas:
    title:        symfony project
    robots:       index, follow
    description:  symfony project
    keywords:     symfony, project
    language:     en

  stylesheets:    [main,layout]

  javascripts:    []

  has_layout:     on
  layout:         layout


