<?php
// auto-generated by sfPropelCrud
// date: 2013/06/19 21:53:31




?>

<?php use_helper('Text') ?>

<h1>popular questions</h1>

<?php foreach($questions as $question): ?>
  <div class="question">

    <div class="interested_block">
      <!-- 部分テンプレート -->
      <!--<?php include_partial('interested_user', array('question' => $question)); ?>-->
      <div class="interested_mark" id="mark_<?php echo $question->getId() ?>">
        <?php echo count(question->getInterests()) ?>
      </div>
    </div>

    <h2><?php echo link_to($question->getTitle(), 'question/show?id='.$question->getId()) ?></h2>

    <div class="question_body">
      <?php echo truncate_text($question->getBody(), 200) ?>
    </div>
  </div>
<?php endforeach;?>

<?php echo link_to ('create', 'question/create') ?>






