<?php
// auto-generated by sfPropelCrud
// date: 2013/06/19 21:53:31
    use_helper('Text');
    use_helper('Text', 'Global');

?>

<h1>recent questions</h1>

<?php foreach($question_pager->getResults() as $question): ?>
    <div class="question">

    <div class="interested_block">
      <div class="interested_mark" id="mark_<?php echo $question->getId() ?>">
        <?php echo $question->getInterestedUsers() ?>
      </div>
    </div>

    <h2><?php echo link_to($question->getTitle(), 'question/show?stripped_title='.$question->getStrippedTitle() ) ?></h2>

    <div class="question_body">
      <?php echo truncate_text($question->getBody(), 200) ?>
    </div>
<?php endforeach;?>

<div id="question_pager">
    <?php echo pager_navigation($question_pager, 'question/recent') ?>
</div>





