<?php
// auto-generated by sfPropelCrud
// date: 2013/06/19 21:53:31
    use_helper('Date');


?>

<div class="interested_block">
    <!-- 部分テンプレート -->
    <!--<?php include_partial('interested_user', array('question' => $question)); ?>-->
    <div class="interested_mark" id="mark_<?php echo $question->getId() ?>">
        <?php echo count(question->getInterests()) ?>
    </div>
</div>

<h2><?php echo $question->getTitle() ?></h2>

<div class="question_body">
    <?php echo $question->getBody() ?>
</di>

<div id="answers">
    <?php foreach($question->getAnswers() as $answer ): ?>
        <div class="answer">
            posted by <?php echo $answer->getUser() ?>
            on <?php echo format_date($answer->getCreatedAt(), 'p') ?>
            <div>
                <?php echo $answer->getBody() ?>
            </div>
        </div>
    <?php endforeach; ?>
</div>

<?php echo link_to('edit', 'question/edit?id='.$question->getId()) ?>
&nbsp;<?php echo link_to('list', 'question/list') ?>
