<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/07/05 04:11:07

$database = new sfPropelDatabase();
$database->initialize(array (
  'phptype' => 'mysql',
  'host' => '127.0.0.1',
  'database' => 'askeet',
  'username' => 'root',
  'password' => 'root',
), 'propel');
$this->databases['propel'] = $database;
