<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/07/05 00:48:32
$this->security = array (
  'add' => 
  array (
    'is_secure' => true,
    'credentials' => 'subscriber',
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
