<?php
// auto-generated by sfValidatorConfigHandler
// date: 2013/07/05 00:51:48

if ($_SERVER['REQUEST_METHOD'] == 'GET')
{
  $validators = array();
  $context->getRequest()->setAttribute('fillin', array (
), 'symfony/filter');
}
else if ($_SERVER['REQUEST_METHOD'] == 'POST')
{
  $validators = array();
  $validators['nicknameValidator'] = new sfStringValidator();
  $validators['nicknameValidator']->initialize($context, array (
  'min' => 5,
  'min_error' => 'nickname must be 5 or more characters',
));
  $validators['userValidator'] = new myLoginValidator();
  $validators['userValidator']->initialize($context, array (
  'password' => 'password',
  'login_error' => 'this account does not exist or you entered a wrong password',
));
  $validatorManager->registerName('nickname', 1, 'your nickname is required', null, null, false);
  $validatorManager->registerValidator('nickname', $validators['nicknameValidator'], null);
  $validatorManager->registerValidator('nickname', $validators['userValidator'], null);
  $validatorManager->registerName('password', 1, 'your password is required', null, null, false);
  $context->getRequest()->setAttribute('fillin', array (
), 'symfony/filter');
}
