<?php
// auto-generated by sfValidatorConfigHandler
// date: 2013/07/05 01:15:39

if ($_SERVER['REQUEST_METHOD'] == 'GET')
{
  $validators = array();
  $context->getRequest()->setAttribute('fillin', array (
), 'symfony/filter');
}
else if ($_SERVER['REQUEST_METHOD'] == 'POST')
{
  $validators = array();
  $validators['bodyValidator'] = new sfStringValidator();
  $validators['bodyValidator']->initialize($context, array (
  'min' => 10,
  'min_error' => 'Please, give some more details',
));
  $validatorManager->registerName('title', 1, 'You must give a title to your question', null, null, false);
  $validatorManager->registerName('body', 1, 'You must provide a brief context for your question', null, null, false);
  $validatorManager->registerValidator('body', $validators['bodyValidator'], null);
  $context->getRequest()->setAttribute('fillin', array (
), 'symfony/filter');
}
